### ISSUE TITLE
Marketplace integration needs to be removed

### ISSUE THREAD

**Issue by herent** [concrete5/concrete5-legacy#1986]
With the legacy branch at EOL, the 5.6 marketplace is being shut down. The marketplace integration should be removed so that it's not making calls to something that no longer exists.

**Comment by JohntheFish** [comment]
Also newsflow.

**Comment by hissy** [comment]
How about return an empty response from c5.org ?
Also, we can send how to migrate to the latest version as newflow.

**Comment by carlos22** [comment]
The marketplace and the newsflow could be disabled in the `config/site.php`:
```
define('ENABLE_INTELLIGENT_SEARCH_HELP',false);
define('ENABLE_NEWSFLOW_OVERLAY',false);
define('ENABLE_MARKETPLACE_SUPPORT',false);
```
Why not make this the default in the next release? This would be a quick fix and does not break anything else.

**Comment by Remo** [comment]
I would review and merge a PR if someone is willing to spend the time to create one, don't have time to do it myself at the moment.

**Comment by Remo** [comment]
Why not remove everything? Is there a chance that someone wants to enable this again? I can't imagine this code has any use, but maybe I'm missing something..

**Comment by carlos22** [comment]
Oh you can remove everything, but that is more work and it is more likely to break something. Feel free to remove everything :-)

**Comment by JohntheFish** [comment]
There could be a whole host of unintended consequences from removing everything, so 5.6.4.0 could soon lead to a need for 5.6.4.1, 5.6.4.2 etc. I don't believe there would be sufficient attention from Portland Labs for that to be feasible. So 5.6.4.0 must be a safe release thats doesn't introduce any new issues that need further updates. We need to think of this as final.

While removing everything would be the purest solution, Unless someone has sufficient free time to do a particularly thorough series of tests, I agree with @carloss22 that simply enforcing 'disable' by default would be most practical because it has lowest risk.
