### ISSUE TITLE
Notice: Use of undefined constant

### ISSUE THREAD

**Issue by ConcreteOwl** [concrete5/concrete5-legacy#1996]
This error is being thrown because concrete/core/libraries/localization.php has on line 72..
if (($locale == 'en_US') && (!ENABLE_TRANSLATE_LOCALE_EN_US)) {
Should it be...
if (($locale == 'en_US') && (!'ENABLE_TRANSLATE_LOCALE_EN_US')) {

**Comment by Remo** [comment]
It's a constant, why would you want to turn this into a string? We should add 'defined' to it, shouldn't we?

**Comment by ConcreteOwl** [comment]
Because the error message went on to say it had assumed 'ENABLE_TRANSLATE_LOCALE_EN_US' and after making that change, the errors went away?

**Comment by Remo** [comment]
Well, it's not just about getting rid of the notice, we should also keep the functionality 😉

**Comment by ConcreteOwl** [comment]
Do you have an alternative solution Remo?

**Comment by ConcreteOwl** [comment]
No alternative solution, then I am happy to leave mine as the best answer for now.

**Comment by mlocati** [comment]
Of course @Remo is right: `ENABLE_TRANSLATE_LOCALE_EN_US` can't be simply replaced with `'ENABLE_TRANSLATE_LOCALE_EN_US'`.

Why?
```php
if (ENABLE_TRANSLATE_LOCALE_EN_US) {
```
means "If the value of the `ENABLE_TRANSLATE_LOCALE_EN_US` constant is not falsy then do something".

But
```php
if ('ENABLE_TRANSLATE_LOCALE_EN_US') {
```
means "If the string `'ENABLE_TRANSLATE_LOCALE_EN_US'` is not empty or zero (that is, always) then do something".

The error message  `Use of undefined constant ENABLE_TRANSLATE_LOCALE_EN_US - assumed 'ENABLE_TRANSLATE_LOCALE_EN_US'` simply means that the `ENABLE_TRANSLATE_LOCALE_EN_US` is not defined, and PHP assumes that the person who wrote the code wanted to write `'ENABLE_TRANSLATE_LOCALE_EN_US'` instead of `ENABLE_TRANSLATE_LOCALE_EN_US`, but it's not the case: we really want the `ENABLE_TRANSLATE_LOCALE_EN_US` constant.

So, the correct fix is
```php
if (($locale == 'en_US') && (!defined('ENABLE_TRANSLATE_LOCALE_EN_US') || !ENABLE_TRANSLATE_LOCALE_EN_US)) {
```

**Comment by ConcreteOwl** [comment]
Thank you Michele for the proper solution.
The only part of your code that I find confusing is `!defined`

**Comment by mlocati** [comment]
>  The only part of your code that I find confusing is `!defined`

The `defined` functions checks if a constant is defined.
See for example https://3v4l.org/W9R1W

Consider this part:
```php
!ENABLE_TRANSLATE_LOCALE_EN_US
```
The `!` symbol means: return `true` if what follows if falsy, or `false` if what follows is not falsy.
So:
- if `ENABLE_TRANSLATE_LOCALE_EN_US` is a defined constant:
  - it returns `true` if the value of the constant `ENABLE_TRANSLATE_LOCALE_EN_US` is falsy
  - it returns `false` if the value of the constant `ENABLE_TRANSLATE_LOCALE_EN_US` is not falsy
- if `ENABLE_TRANSLATE_LOCALE_EN_US` not defined:
  - PHP assumes that we wanted to write `'ENABLE_TRANSLATE_LOCALE_EN_US'` (that is, a string) instead of `ENABLE_TRANSLATE_LOCALE_EN_US` (a constant)
  - so, it returns `false` (since the string `'ENABLE_TRANSLATE_LOCALE_EN_US'` is not empty and is not `'0`)

That's not what we really want. We want `false` if the constant `ENABLE_TRANSLATE_LOCALE_EN_US` is not defined, like if it was defined with a falsy value.

So,
```php
!defined('ENABLE_TRANSLATE_LOCALE_EN_US') || !ENABLE_TRANSLATE_LOCALE_EN_US)
```
returns `true` if the constant `ENABLE_TRANSLATE_LOCALE_EN_US` is not defined, or if it's defined and it contains a falsy value

**Comment by ConcreteOwl** [comment]
Got it, Thank you for having the patience to explain that to me.
